{ "adc", SCHED_PRIORITY_DEFAULT, 2048, adc_main },
{ "ArduPlane", SCHED_PRIORITY_DEFAULT, 4096, ArduPlane_main },
{ "blinkm", SCHED_PRIORITY_DEFAULT, 2048, blinkm_main },
{ "bmp180", SCHED_PRIORITY_DEFAULT, 2048, bmp180_main },
{ "delay_test", SCHED_PRIORITY_DEFAULT, 2048, delay_test_main },
{ "fmu", SCHED_PRIORITY_DEFAULT, 2048, fmu_main },
{ "gps", SCHED_PRIORITY_DEFAULT, 2048, gps_main },
{ "hil", SCHED_PRIORITY_DEFAULT, 2048, hil_main },
{ "hmc5883", SCHED_PRIORITY_DEFAULT, 4096, hmc5883_main },
{ "i2c", SCHED_PRIORITY_DEFAULT, 4096, i2c_main },
{ "mavlink", SCHED_PRIORITY_DEFAULT, 2048, mavlink_main },
{ "mavlink_onboard", SCHED_PRIORITY_DEFAULT, 2048, mavlink_onboard_main },
{ "mixer", SCHED_PRIORITY_DEFAULT, 4096, mixer_main },
{ "mpu60x0", SCHED_PRIORITY_DEFAULT, 4096, mpu60x0_main },
{ "param", SCHED_PRIORITY_DEFAULT, 4096, param_main },
{ "perf", SCHED_PRIORITY_DEFAULT, 2048, perf_main },
{ "reboot", SCHED_PRIORITY_DEFAULT, 2048, reboot_main },
{ "sdlog", SCHED_PRIORITY_MAX - 30, 2048, sdlog_main },
{ "sensors", SCHED_PRIORITY_MAX-5, 4096, sensors_main },
{ "tests", SCHED_PRIORITY_DEFAULT, 12000, tests_main },
{ "top", SCHED_PRIORITY_DEFAULT - 10, 3000, top_main },
{ "uorb", SCHED_PRIORITY_DEFAULT, 4096, uorb_main },
