APPNAME   	 = pwm_output
PRIORITY    = SCHED_PRIORITY_MAX-5
STACKSIZE    = 4096
CSRCS   	 = pwm_output.c
INCLUDES	 = $(TOPDIR)/arch/arm/src/stm32 $(TOPDIR)/arch/arm/src/common
include $(APPDIR)/mk/app.mk

