APPNAME   	 = read_battery_voltage
PRIORITY    = SCHED_PRIORITY_MAX-5
STACKSIZE    = 4096
CSRCS   	 = read_battery_voltage.c
INCLUDES	 = $(TOPDIR)/arch/arm/src/stm32 $(TOPDIR)/arch/arm/src/common
include $(APPDIR)/mk/app.mk

