APPNAME   	 = pwm_input
PRIORITY    = SCHED_PRIORITY_MAX-5
STACKSIZE    = 4096
CSRCS   	 = pwm_input.c
include $(APPDIR)/mk/app.mk
INCLUDES	 = $(TOPDIR)/arch/arm/src/stm32 $(TOPDIR)/arch/arm/src/common
